project_name: rox_listener

builds:
  - id: rox_listener
    main: ./cmd/rox_listener
    binary: rox_listener
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: rox_listener
    ids: [rox_listener]
    formats: [tar.gz]
    name_template: "rox_listener_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: touchmeangel
    name: rox_listener